### ISSUE TITLE
I use Nginx

### ISSUE THREAD

**Issue by kmkmahesh** [nathan242/php-mvc#1]
Hi nathan,

can you please post the nginx config also, i cannot use apache as of now, i want to create a own MVC which can work with RBAC with multiple levels

**Comment by nathan242** [comment]
I don't currently have access to an Nginx environment to test but this should be what you need:

```
server {
    listen 80;
    server_name example.com;
    root /var/www/php-mvc/Application/www;
 
    index index.php;
 
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }
 
    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_pass unix:/run/php/php8.1-fpm.sock;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }
}
```
Edit the above to match your environment (at least root and fastcgi_pass need to be checked). Let me know if it works and I will update the README at some point.

**Comment by nathan242** [comment]
Please let me know of the above nginx config works.
